sudo: false
language: python
services:
  - memcached
python:
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - npm install jshint
  - npm install mocha
  - npm install jquery
  - npm install jsdom@3
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 myuw/ --exclude=migrations,myuw/static
  - jshint myuw/static/js/  --verbose
  - mocha myuw/static/js/test/ --recursive
  - coverage run --source=myuw/ --omit=myuw/migrations/* manage.py test myuw
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
