sudo: false
language: python
services:
  - memcached
  - mysql
python:
  - "2.7"
env:
  matrix:
    - DB=sqlite3
    - DB=mysql
  global:
    - TRAVIS_NODE_VERSION="4"
install:
  - pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install MySQL-python
  - npm install jshint
  - npm install mocha
  - npm install jquery
  - npm install moment
  - npm install moment-timezone
  - npm install datejs
  - npm install jsdom@3
  - npm install istanbul
  - npm install sinon
  - npm install coveralls
  - gem install coveralls-lcov
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate

  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create database myuw'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create user "myuw" identified by "my_pass"'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'grant all on *.* to myuw'; fi
script:
  - which mocha
  - which _mocha
  - which istanbul
  - ls -l ./node_modules/.bin/_mocha
  - ls -l ./node_modules/mocha/bin/_mocha
  - pep8 myuw/ --exclude=migrations,myuw/south_migrations,myuw/static
  # Find </br> tags
  - grep -re '<\s*/\s*br\s*>' myuw/templates/ ; test $? -eq 1
  - jshint myuw/static/js/  --verbose
  - mocha myuw/static/js/test/ --recursive
  - istanbul cover --include-all-sources -x "**/vendor/**" -x "**/site-packages/**" ./node_modules/mocha/bin/_mocha -- -R spec myuw/static/js/test/
  - FORCE_VIEW_TESTS=1 coverage run --source=myuw/ --omit=myuw/migrations/* manage.py test myuw
  - coveralls-lcov -v -n coverage/lcov.info > js-coverage.json
after_script:
  - coveralls --merge=js-coverage.json
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
