sudo: false
language: python
services:
  - memcached
  - mysql
python:
  - "2.7"
  # - "3.6"
env:
  matrix:
    - DB=sqlite3
    # - DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create database myuw'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'create user "myuw" identified by "my_pass"'; fi
  - if [ "$DB" = "mysql" ] ; then mysql -u root -e 'grant all on *.* to myuw'; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] ; then pip install MySQL-python; fi
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.6" ] ; then pip install mysqlclient; fi

  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - npm install
  - gem install coveralls-lcov
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate
  - npm list

script:
  - pycodestyle myuw/ --exclude=migrations,myuw/static
  # Find </br> tags
  - grep -re '<\s*/\s*br\s*>' myuw/templates/ ; test $? -eq 1
  - grep -r 'static/' myuw/ | grep -v /test/ | grep -v washington.edu/static; test $? -eq 1
  - npm run jshint myuw/static/js/  --verbose
  - npm run mocha myuw/static/js/test/ --recursive
  - npm run test
  - FORCE_VIEW_TESTS=1 coverage run --source=myuw/ --omit=myuw/migrations/* manage.py test myuw
  - coveralls-lcov -v -n coverage/lcov.info > js-coverage.json
after_script:
  - coveralls --merge=js-coverage.json
notifications:
