sudo: required

language: python
python:
  - 3.6

services:
  - docker
  - memcached

os:
  - linux

env:
  global:
    - RELEASE_NAME="myuw"
    - DJANGO_APP="myuw"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
    - DEPLOY_SCRIPT_BASE=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master
    - secure: "Ms3F/3R08D7/DN+Ix/sbc8cGbdpF6F4lUL5gWSYAhjaya82tKLbu0WmfagSCWTUkMDBSP1RpPHJYNmOaCv6S9iXLyZ9t3ErNLhLY44VgcC0b94ebZYk7Tl9zRktodbTkq7LBBVUWNEPzdMZR5nL9H86m8h6D85YX/SheXynQZCE="
    - secure: "SQFn4ziHQMZ7HnHJ0G4hiaam+CaDKLgRMe3XHiOfR8vDI9ziQ2C1qL4he2G51iSgdD8WyZkGCiJJ4SjcgdNGuXrOpKpPojFwTwHumfGZq/eebU3RBxEITj7zfbedSf6A9wWsgLzNToQ/vOQtl/G0WD3gCUaGh0xjZ6VrJkmlIho="
    - secure: "JMVV0SG9a04GNq2F304OWnkf6xIaI87Nhf45RoZoU717IMi+xvrz8qX3fYibcv/15eLt+XdeQeu0CxM8/ZSlrReWXf/0/9Qe7m8SxoQj6W35kBIHOEfPln06hP5fq0ruhg5k4eZKQrwCwoeIt3+iOWCtKE+yQJyWvd92t1WX080="

install:
  - docker build --target app-container -t "$IMAGE_TAG" .
  - docker build -t app-test-container .

before_script:
  - gem install coveralls-lcov
  - pip install coverage
  - pip install coveralls

script:
  - docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev" -e "AUTH=SAML_MOCK" -e "MEMCACHED_SERVER_COUNT=1" -e "MEMCACHED_SERVER_SPEC=localhost" app-test-container bash -c ". ./travis-ci/test.sh"

after_success:
  - cp /tmp/.coverage.* /tmp/lcov.info .
  - coverage combine
  - coveralls-lcov -v -n lcov.info > js-coverage.json
  - coveralls --merge=js-coverage.json
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      case "$TRAVIS_BRANCH" in
        "master")
          export APP_INSTANCE="prod";
          ;;
        "qa")
          export APP_INSTANCE="test";
          ;;
        "fix/MUWM-3830")
          export APP_INSTANCE="dev";
          ;;
        *)
          unset APP_INSTANCE
          ;;
      esac
      if [[ "$APP_INSTANCE" ]]; then
        curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash;
      fi
    fi

cache:
  directories:
    - "$HOME/helm"
    - "$HOME/kubeval"
