sudo: false
language: python
python:
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - npm install jshint
  - npm install mocha
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 myuw_mobile/ --exclude=migrations
  - jshint myuw_mobile/static/js/  --verbose
  - mocha myuw_mobile/static/js/test/ --recursive
  - coverage run --source=myuw_mobile/ --omit=myuw_mobile/migrations/* manage.py test myuw_mobile
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
sudo: false
